### PR TITLE
Refactoring and clean up performed

### PR DESCRIPTION
**Pull request by Siemienik**
I want only perform little cleanup before I start #7. As often happen I did much more than initial planned. So these changes I placed into separated PR. I will be thankful for constructive feedback 🙀

* Extract strategies,
* Replace switch by mapper, 
* Introduce ImportType enum and type aliases,
* Improve documentation,
* Handling incorrect type param value more explicitly.

### CODE REVIEW

**Comment by lowkeypriority** [comment]
Some questions about TODOs in files:
Do you want to replace `export default` with `export` only?
Or also add `index` file for directory modules future importing via directory name?

**Comment by Siemienik** [comment]
> Do you want to replace export default with export only?

Yes, simple export is much more convenient for maintaining, but I can't change it at once - this probably breaks backward compatibility for some package users - I don't know how their uses `xlsx-import`. So in care of all, I have plan to:

1. add "simple" export side-by-side to this "default" export
2. deprecate "default" export
3. wait a half year
4. remove "default" export
5. publish lib with only "simple" export (probably as minor version)

(as "simple" export I mean without `default`)

> Or also add index file for directory modules future importing via directory name?

'modules' ? Did you asked about `src/mappers/index.ts`? If yes I answered below. If no, could I please you for more explanation?

I move this into separate directory because it isn't part of `Import` logic (kept in `src/`), it isn't also part of `ImportStrategies` (`src/strategies`).
Moving it into 'src/mappers' creates new independent part of library which is open further growing by increasing ready to use mappers like numberMapper.

btw. I really dislike using of `index.ts` name for any file, However in this case, create second file will be quite strange.

**Comment by lowkeypriority** [comment]
> Did you asked about `src/mappers/index.ts`

Yes, thanks for the answer

> So in care of all, I have plan to...

How about using the * "deprecated" * warnings? So do we preserve legacy and create new code, or do we just wake up a second branch with new features?

**Comment by Siemienik** [comment]
> So do we preserve legacy and create new code
In some period of time yes, finally (after some months pasts) code should be cleaned up.

**Comment by Siemienik** [comment]
as no one has any comment I decided to merge it.

Do you want to support my work? [**❤️ Sponsor me**](https://github.com/sponsors/Siemienik)

**Pull request merged**
