### PR TITLE
Add test command for nodejs and nodejs-ts samples + upgrade 

### PR DESCRIPTION
**Pull request by Siemienik**
_In according to new version released #60_

+ Added simple test for each to prove that it works

@Metastasis want you review?

### CODE REVIEW

**Comment by Siemienik** [comment]
@Metastasis I see that you add :+1: for PR description. Is it an approval?

**Comment by Metastasis** [comment]
@Siemienik in general yes, but Im not sure if test command will run in windows (Im using windows). I need to verify this, If its not working I will submit PR then

**Comment by Siemienik** [comment]
> @Siemienik in general yes, but Im not sure if test command will run in windows (Im using windows). I need to verify this, If its not working I will submit PR then

Good question

**Comment by Metastasis** [comment]
@Siemienik 
Well, It doesn't work:)

**Comment by Siemienik** [comment]
> @Siemienik
> Well, It doesn't work in windows:)

Thank you for information, I'm going to fix it tomorrow ;-)

**Comment by Siemienik** [comment]
@Metastasis could I ask you to check it again?

**Comment by Metastasis** [comment]
@Siemienik
Its works

**Pull request merged**
