### PR TITLE
Split mapper

### LINKED ISSUE #24: Add splitMapper into mappers
Part of #21

# TODO:

1. [x] Create file `src/mappers/splitMapper.ts` with function matches to type ` (v: string): string[]`. Which for any input try to return only lower case string.
2. [x] reexport it in `src/mappers/index.ts`
3. [x] Prove that it works in unit test (create new one in `tests/unit/mappers.test.ts`)
4. [x] Describe it in Readme.md 

## test data provider:

```
const lowerCaseDp = [
  { inValue: '', expectedResult: [] },
  { inValue: 'asd', expectedResult: ['asd'] },
  { inValue: 'asd,', expectedResult: ['asd',''] },
  { inValue: 'asd,asd2', expectedResult: ['asd','asd2'] },
  { inValue: 'true,1, expectedResult: ['true','1'] },
]
```

# Further (not in scope of this issue)

* setting for `separator`
* setting for `itemMapper`

### PR DESCRIPTION
**Pull request by lowkeypriority**
## Description

I've been added split mapper and unit test for it.
Also added a description in README, but I don't know how to write an axample :\

Closes #24

## "Roadmap"

- `splitMapper`
  - [x] Add file
  - [x] Reexport in `mappers/index.ts`
  - [x] Add unit test
  - [ ] Add section in README

### CODE REVIEW

**Comment by Siemienik** [comment]
@lowkeypriority it's nice to see your PR 😸 
I have two suggestions for you:
1. could I ask you to do one issue in one PR? the fewer scope is much easier to review and maintain :) Additionally, it may be much quicker merge into master
2. for the split mapper, may I recommend to create a factory? Something like that:
```ts
const factory = (options) => {
  const splitMapper = (value) => value.split(options.separator);

  splitMaper.separator = (separator) => factory({...options, separator});

  return splitMapper;
}

export const splitMapper = factory({separator: ','});
```

usage:

```js
importer.GetAllItems({
  workshet:'Authors',
  type: ' list',
  columns:[
     {key:"fullname", index:1},
     {key: "books", index:2, mapper:splitMapper}, // map from `"book1,book2"` to `["book1","book2"]`
     {key: "adwards", index:3, mapper:splitMapper.separator(' && ')}, // map from `"2020 Adward && 2019 Adward"` to `["2020 Adward","2019 Adward"]`
  ]
});

**Comment by Siemienik** [comment]
ups.. It wasn't expected to close it... It was done automatically after #20 become merged

**Comment by lowkeypriority** [comment]
@Siemienik thanks for review. I'll try to rewrite mappers to factory

Also I'll rename issue – one issue - one PR is food practice :)

**Comment by lowkeypriority** [comment]
@Siemienik Hello again.
I tried to implement the factory pattern but without success:
1. I've created abstract class for mappers:
```typescript
export abstract class Mapper {
  private options: object

  constructor(options: object) {
    this.options = options
  }

  abstract valueOf(value: string): string | string[]
}
```
2. Made `SplitMapper` class extended from `Mapper`:
```typescript
import { Mapper } from "./mapperFactory"

export class SplitMapper extends Mapper {
  constructor(options: object) {
    super({...options, separator: ','})
  }

  valueOf(value: string) {
    value.split(this.options.separator)
  }

  separator(separator: string) {
    this.options.separator = separator
  }
}
```

But this solution is not good at all - it contains TypeGuard bugs and, in my opinion, lacks a good abstraction.

Can you help with this? Any advice?

**Comment by Siemienik** [comment]
@lowkeypriority code what I write works:
image

there is only lack of types.

As a mappers is used as lambda function matches to: `(value: string): any` it isn't required to introduce classes and abstracts.

**Comment by Siemienik** [comment]
> Can you help with this? Any advice?

1. If I were doing this issue, probably I would like to create type `ValueMapper<TResult>` in `src/config/ValueMapper.ts` and use it in:

* https://github.com/Siemienik/xlsx-import/blob/master/src/config/IFieldConfig.ts#L5
* https://github.com/Siemienik/xlsx-import/blob/master/src/config/IColumnConfig.ts#L4

2. Then  create additional type: (above mapper implementation in same file like splitMapper)

```ts
  type SplitMapper = 
     ValueMapper<Array<string>>  // fulfil mapper behaviour 
     & {separator: (separator:string) => SplitMapper};` // adding api for customisations
```

3. Options params may be also written like that: (It is quite convenient as long as has few options inside 😄 
```
const factory = ({separator: string}) => {
  ...
}
```

**Comment by Siemienik** [comment]
@lowkeypriority I've just updated the `master` branch. I added there the simplest example for a mapper (which essentially does nothing):

https://github.com/Siemienik/xlsx-import/pull/29/files#diff-1077c8ee50f57ba4294c63bd9a939366R1-R3

and test for it:

https://github.com/Siemienik/xlsx-import/pull/29/files#diff-a8ab071a67e214d9a2ff48288e4f1538R1-R31

I suppose it will be handful for you 😸

**Comment by Siemienik** [comment]
@lowkeypriority how do you up to? Is any way how can I help you?

**Comment by Siemienik** [comment]
suddenly I have to close this PR because lack of activity here, please open new one if needed

**Pull request closed without merging**
